[variables]
NPM_CONFIG_UPDATE_NOTIFIER = 'false'
NPM_CONFIG_FUND = 'false'

# install nodejs, npm and jq packages
[phases.setup]
nixPkgs = ['nodejs', 'npm', 'jq']

# build the Angular app
[phases.build-angular]
dependsOn = ['setup']
cmds = ['npm install', 'npm run build']

# download caddy
[phases.caddy]
dependsOn = ['build-angular']
nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301' # Caddy v2.8.4
nixPkgs = ['caddy']

# format Caddyfile
[phases.fmt]
dependsOn = ['caddy']
cmds = ['caddy fmt --overwrite Caddyfile']

# start: query outputPath and start Caddy
[start]
cmd = '''
echo "Extracting Angular output path..."
export ANGULAR_OUTPUT_PATH=$(jq -r "[.projects[] | .architect.build.options.outputPath][0]" angular.json)
echo "ANGULAR_OUTPUT_PATH=$ANGULAR_OUTPUT_PATH"
echo "PORT=$PORT"
ls -la $ANGULAR_OUTPUT_PATH/browser || echo "Browser output folder not found!"
exec caddy run --config Caddyfile --adapter caddyfile 2>&1
'''
